version: '3'

services:
  next-template:
    image: next_template
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_LOG_LEVEL=debug
      - NEXT_PUBLIC_API_URL=http://your-server-name
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
